#!/bin/bash

export DOCKER_FILE          = docker-compose.yml
export BASE_IMAGE_NAME	    = ubuntu
export BASE_IMAGE_TAG		= 16.04
export BASE_IMAGE		    = $(BASE_IMAGE_NAME):$(BASE_IMAGE_TAG)

export IMAGE_NAME	        = interdatafr/docker-nginx-ha
export IMAGE_VERSION	    = 1.0

export IMAGE_TAG	        = v$(IMAGE_VERSION)